steps:
  - trigger: slave-pipeline
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
  
  - wait
  
  - block: "Wait for Unblock Signal"
  -  wait
  - label: "Unblock Slave Pipeline"
    command: |
      echo $BUILDKITE_PIPELINE_NAME
      curl -H "Authorization: Bearer bkua_5b60deaf82f5775af82478873bab212805995acc" \
        -X PUT "https://api.buildkite.com/v2/organizations/rtctek/pipelines/$BUILDKITE_PIPELINE_NAME/builds/$BUILDKITE_BUILD_NUMBER/jobs/$BUILDKITE_JOB_ID/unblock" \
        -H "Content-Type: application/json" \
        -d '{
          "fields": {
            "Who is unblocking this stage?": "gunjan"
            }
        }'
