steps:
  - trigger: slave-pipeline
    async: true
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
    key: "trigger-slave-pipeline"
  
  - wait
  
  - block: "Wait for Unblock Signal"
  
  - label: "Unblock Slave Pipeline"
    command: |
      curl -H "Authorization: Bearer bkua_5b60deaf82f5775af82478873bab212805995acc" \
        -X PUT "https://api.buildkite.com/v2/organizations/rtctek/pipelines/slave-pipeline/builds/12/jobs/018ebd4e-2a8c-4534-b5e4-e01ecde0dd64/unblock" \
        -H "Content-Type: application/json" \
        -d '{
        "fields": {
          "Who is unblocking this stage?": "gunjan"
        }'
