steps:
  - trigger: slave-pipeline
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
  
  - wait
  
  
  - label: "Unblock Slave Pipeline"
    command: |
      unblock_url=$(jq -r '.jobs[3].unblock_url')
      echo $unblock_url
