steps:
  - trigger: slave-pipeline
    async: true
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
    key: "trigger-slave-pipeline"
  
  - wait
  
  - block: "Wait for Unblock Signal"
    fields:
      - text: "Unblocker Name"
        key: "unblocker_name"
        required: true
      - text: "Unblocker Email"
        key: "unblocker_email"
        required: true
  
  - label: "Unblock Slave Pipeline"
    command: |
      curl -H "Authorization: Bearer $BUILDKITE_TOKEN" \
        -X PUT "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORG/pipelines/$SLAVE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/unblock" \
        -H "Content-Type: application/json" \
        -d '{}'
