steps:
  - trigger: slave-pipeline
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
  
  - wait
  
  
  - label: "Unblock Slave Pipeline"
    command: |
      curl -H "Authorization: Bearer bkua_5b60deaf82f5775af82478873bab212805995acc" -X GET "https://api.buildkite.com/v2/organizations/rtctek/pipelines/master-testing-pipeline/builds/$BUILDKITE_BUILD_NUMBER" > master.json &&
      slave_build= (jq '.jobs[1].triggered_build.number' master.json) &&
      echo $BUILDKITE_BUILD_NUMBER &&
      echo $slave_build
