steps:
    - block: "Unblock!"
      fields:
        - text: "Who is unblocking this stage?"
          key: "unblocker"
          hint: "Provide your work email"
    - wait
          
    - label: "dev"
      key: "dev"
      command: echo "this is dev"
      
    - wait
    
    - blocks:
        - name: Trigger Slave Pipeline
          script:
            - buildkite-agent trigger-pipeline --branch=main slave-testing-pipeline
