steps:
  - trigger: slave-pipeline
    build:
      message: "Triggered by Master Pipeline"
      commit: "HEAD"
      branch: "main"
  
  - wait
  
  
  - label: "Unblock Slave Pipeline"
    command: echo "$unblock_url"
