  steps: 
    - label: "dev"
      key: "dev"
      command: echo "this is dev"
      
    - wait
    
    - block: 
      fields:
        - text: "Who is unblocking this stage?"
          key: "name"
          hint: "Provide your work email"
          
    
    - label: "staging"
      key: "staging"
      command: |
        echo "this is staging stage"
      
    - wait
 
    - label: "prod"
      key: "prod"
      command: echo "this is prod stage"
