  steps: 
    - label: "dev"
      key: "dev"
      command: echo "this is dev"
      
    - wait
    
    - block: "Unblock!"
      fields:
        - text: "Who is unblocking this stage?"
          key: "unblocker"
          hint: "Provide your work email"
          
    - wait
    - label: "Unblock Slave Pipeline"
      command: |
        echo $BUILDKITE_PIPELINE_NAME
        curl -H "Authorization: Bearer bkua_5b60deaf82f5775af82478873bab212805995acc" \
          -X PUT "https://api.buildkite.com/v2/organizations/rtctek/pipelines/$BUILDKITE_PIPELINE_NAME/builds/$BUILDKITE_BUILD_NUMBER/jobs/$BUILDKITE_JOB_ID/unblock" \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
              "Who is unblocking this stage?": "gunjan"
              }
          }'
          
    - label: "staging"
      key: "staging"
      command: |
        echo "this is staging stage"
      
    - wait
 
    - label: "prod"
      key: "prod"
      command: echo "this is prod stage"
